# AUTOGENERATED! DO NOT EDIT! File to edit: 04_controller.ipynb (unless otherwise specified).

__all__ = ['Controller']

# Cell
from .playfield import Playfield
from .piece_loader import PieceLoader

try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

if IN_NOTEBOOK:
    from IPython.display import display

class Controller:
    def process(self, line:str) -> Playfield:
        pf = Playfield()
        loader = PieceLoader()
        for instr in line.split(','):
            shape, col = instr[0].lower(), int(instr[1])
            cleared_lines = pf.add_with_clear(loader.pieces[shape], col)
            if IN_NOTEBOOK:
                display(pf)
            #print(f'cleared {cleared_lines} lines')
        return pf